name: html2md
description: A library for converting HTML to Markdown. It supports CommonMark, simple table and custom converting rules.
version: 1.3.2
homepage: https://github.com/jarontai/html2md

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html: any
  collection: any

dev_dependencies:
  lints: any
  test: any
